USE customer_behavior;
select * from customer;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
       ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))), 2) AS Average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY Average_review_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;


-- Q11. which age group generates the lowest revenue?
select age_group,sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue ASC
limit 1;

-- Q12.What is the average purchase amount for each age group?
select age_group, avg(purchase_amount) as avg_purchase
from customer
group by age_group
order by avg_purchase DESC;

-- Q13. which gender generates the lowest revenue?
SELECT gender, AVG(purchase_amount) AS avg_purchase
FROM customer
GROUP BY gender;

-- Q14. which age group has the highest number of purchase?
SELECT age_group, COUNT(*) AS total_purchases
FROM customer
GROUP BY age_group
ORDER BY total_purchases DESC
LIMIT 1;

-- Q15. which age group shops most frequently?
SELECT age_group, frequency_of_purchases, COUNT(*) AS total_customers
FROM customer
GROUP BY age_group, frequency_of_purchases
ORDER BY total_customers DESC;

-- Q16. which gender gives the highest average review rating?
SELECT gender, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY gender
ORDER BY avg_rating DESC;

-- Q17.	Which age group tends to purchase more premium items?
SELECT age_group, COUNT(*) AS premium_purchases
FROM customer
WHERE purchase_amount > (
    SELECT AVG(purchase_amount) FROM customer
)
GROUP BY age_group
ORDER BY premium_purchases DESC;

-- Q18.Which item is purchased the most?
SELECT item_purchased, COUNT(*) AS total_purchases
FROM customer
GROUP BY item_purchased
ORDER BY total_purchases DESC
LIMIT 1;

-- Q19.Which item generates the highest revenue?
SELECT item_purchased, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY item_purchased
ORDER BY total_revenue DESC
LIMIT 1;

-- Q20.Which category has the highest sales revenue?
SELECT category, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 1;

-- Q21.Which category has the lowest sales revenue?
SELECT category, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category
ORDER BY total_revenue ASC
LIMIT 1;

-- Q22.What is the average purchase amount by category?
SELECT category, AVG(purchase_amount) AS avg_purchase
FROM customer
GROUP BY category
ORDER BY avg_purchase DESC;


-- Q23.Which product has the lowest average rating?
SELECT item_purchased, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 1;

-- Q24.Which category has the highest number of customer ratings?
SELECT category, COUNT(review_rating) AS total_ratings
FROM customer
GROUP BY category
ORDER BY total_ratings DESC
LIMIT 1;

-- Q25.Which product category is most frequently purchased by repeat customers?
SELECT category, COUNT(*) AS repeat_purchases
FROM customer
WHERE previous_purchases > 1
GROUP BY category
ORDER BY repeat_purchases DESC
LIMIT 1;

-- Q26.Which product performs best during each season?
SELECT season, item_purchased, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY season, item_purchased
ORDER BY season, total_revenue DESC;

-- Q27.Which item is most popular among subscribed customers?
SELECT item_purchased, COUNT(*) AS total_purchases
FROM customer
WHERE subscription_status = 'Yes'
GROUP BY item_purchased
ORDER BY total_purchases DESC
LIMIT 1;

-- Q28.Which product category attracts the highest spending customers?
SELECT category, AVG(purchase_amount) AS avg_spending
FROM customer
GROUP BY category
ORDER BY avg_spending DESC
LIMIT 1;

-- Q29.Which items are most frequently purchased when discounts are applied?
SELECT item_purchased, COUNT(*) AS discounted_sales
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY discounted_sales DESC;

-- Q30.Which category has the most consistent sales across seasons?
SELECT category, season, SUM(purchase_amount) AS total_sales
FROM customer
GROUP BY category, season
ORDER BY category, season;

-- Q31.What is the total revenue generated from all purchases?
SELECT SUM(purchase_amount) AS total_revenue
FROM customer;

-- Q32.Which location generates the highest revenue?
SELECT location, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue DESC
LIMIT 1;

-- Q33.Which location generates the lowest revenue?
SELECT location, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY location
ORDER BY total_revenue ASC
LIMIT 1;

-- Q34.Which season generates the highest total revenue?
SELECT season, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue DESC
LIMIT 1;

-- Q35.Which season generates the lowest total revenue?
SELECT season, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY season
ORDER BY total_revenue ASC
LIMIT 1;

-- Q36.Which location has the highest number of transactions?
SELECT location, COUNT(*) AS total_transactions
FROM customer
GROUP BY location
ORDER BY total_transactions DESC
LIMIT 1;

-- Q37.Which location has the lowest number of transactions?
SELECT location, COUNT(*) AS total_transactions
FROM customer
GROUP BY location
ORDER BY total_transactions ASC
LIMIT 1;

-- Q38.Which product size generates the highest revenue?
SELECT size, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY size
ORDER BY total_revenue DESC
LIMIT 1;

-- Q39.Which color generates the most sales revenue?
SELECT color, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY color
ORDER BY total_revenue DESC
LIMIT 1;

-- Q40.Which size has the lowest demand?
SELECT size, COUNT(*) AS total_sales
FROM customer
GROUP BY size
ORDER BY total_sales ASC
LIMIT 1;

-- Q41.Which location generates the highest number of high-value purchases?
SELECT location, COUNT(*) AS high_value_sales
FROM customer
WHERE purchase_amount > 50
GROUP BY location
ORDER BY high_value_sales DESC
LIMIT 1;

-- Q42.Which customers have the highest number of previous purchases?
SELECT customer_id, previous_purchases
FROM customer
ORDER BY previous_purchases DESC
LIMIT 10;

-- Q43.Which frequency of purchase category is most common?
SELECT frequency_of_purchases, COUNT(*) AS count
FROM customer
GROUP BY frequency_of_purchases
ORDER BY count DESC
LIMIT 1;

-- Q44.Which frequency group generates the highest revenue?
SELECT frequency_of_purchases, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY frequency_of_purchases
ORDER BY total_revenue DESC
LIMIT 1;

-- Q45.Which customers purchase most frequently without subscription?
SELECT customer_id, frequency_of_purchases
FROM customer
WHERE subscription_status = 'No'
ORDER BY frequency_of_purchases DESC
LIMIT 10;

-- Q46.Which customer type spends the most but does not use discounts?
SELECT gender, purchase_amount
FROM customer
WHERE discount_applied = 'No'
ORDER BY purchase_amount DESC
LIMIT 10;

-- Q47.Which age group prefers which color the most?
SELECT age_group, color, COUNT(*) AS count
FROM customer
GROUP BY age_group, color
ORDER BY age_group, count DESC;

-- Q48.Which purchase frequency group has high sales but no subscription and no discount?
SELECT frequency_of_purchases, SUM(purchase_amount) AS total_sales
FROM customer
WHERE subscription_status = 'No' AND discount_applied = 'No'
GROUP BY frequency_of_purchases
ORDER BY total_sales DESC
LIMIT 1;

-- Q49.Which customers with subscriptions purchase more frequently?
SELECT customer_id, frequency_of_purchases
FROM customer
WHERE subscription_status = 'Yes'
ORDER BY frequency_of_purchases DESC
LIMIT 10;

-- Q50.Which age group has the highest repeat purchase rate?
SELECT age_group, SUM(previous_purchases) AS total_previous_purchases
FROM customer
GROUP BY age_group
ORDER BY total_previous_purchases DESC
LIMIT 1;

-- Q51.Which product category is most popular among repeat customers?
SELECT category, COUNT(*) AS count
FROM customer
WHERE previous_purchases > 0
GROUP BY category
ORDER BY count DESC
LIMIT 1;

-- Q52.Which customers give high ratings but purchase less frequently?
SELECT customer_id, review_rating, frequency_of_purchases
FROM customer
WHERE review_rating >= 4
ORDER BY frequency_of_purchases ASC
LIMIT 10;

-- Q53.Which customer segment contributes most to loyalty purchases?
SELECT age_group, SUM(previous_purchases) AS total_loyalty_purchases
FROM customer
GROUP BY age_group
ORDER BY total_loyalty_purchases DESC
LIMIT 1;

-- Q54.Which customers have high previous purchases but low current spending?
SELECT customer_id, previous_purchases, purchase_amount
FROM customer
ORDER BY previous_purchases DESC, purchase_amount ASC
LIMIT 10;


-- Q55.How many customers used discounts?
SELECT COUNT(*) AS customers_used_discount
FROM customer
WHERE discount_applied = 'Yes';

-- Q56.How many customers purchased without discounts?
SELECT COUNT(*) AS customers_no_discount
FROM customer
WHERE discount_applied = 'No';

-- Q57.Which product category benefits the most from discounts?
SELECT category, COUNT(*) AS discount_count
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY category
ORDER BY discount_count DESC
LIMIT 1;

-- Q58.Which locations have the highest discount usage?
SELECT location, COUNT(*) AS discount_count
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY location
ORDER BY discount_count DESC
LIMIT 5;

-- Q59.Which age group uses discounts the most?
SELECT age_group, COUNT(*) AS discount_count
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY age_group
ORDER BY discount_count DESC
LIMIT 1;

-- Q60.Which products are most often bought with discounts?
SELECT item_purchased, COUNT(*) AS discount_count
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY item_purchased
ORDER BY discount_count DESC
LIMIT 5;

-- Q61.What percentage of customers have active subscriptions?
SELECT 
    ROUND(
        (SUM(CASE WHEN subscription_status = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*),
        2
    ) AS subscription_percentage
FROM customer;

-- Q62.Which subscription customers purchase most frequently?
SELECT customer_id, frequency_of_purchases
FROM customer
WHERE subscription_status = 'Yes'
ORDER BY frequency_of_purchases DESC
LIMIT 10;

-- Q63.Which locations have the highest subscription rates?
SELECT location, COUNT(*) AS subscriber_count
FROM customer
WHERE subscription_status = 'Yes'
GROUP BY location
ORDER BY subscriber_count DESC
LIMIT 5;

-- Q64.Which product categories are most popular among subscribers?
SELECT category, COUNT(*) AS subscriber_count
FROM customer
WHERE subscription_status = 'Yes'
GROUP BY category
ORDER BY subscriber_count DESC
LIMIT 3;

-- Q65.Does subscription increase repeat purchases?
SELECT subscription_status, AVG(previous_purchases) AS avg_previous_purchases
FROM customer
GROUP BY subscription_status;

-- Q66.Which product categories are un-popular among subscribers?
SELECT category, COUNT(*) AS subscriber_count
FROM customer
WHERE subscription_status = 'Yes'
GROUP BY category
ORDER BY subscriber_count ASC
LIMIT 1;

-- Q67.Which payment method is used most frequently?
SELECT payment_method, COUNT(*) AS usage_count
FROM customer
GROUP BY payment_method
ORDER BY usage_count DESC
LIMIT 1;

-- Q68.Which payment method generates the highest revenue?
SELECT payment_method, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY payment_method
ORDER BY total_revenue DESC
LIMIT 1;

-- Q69.Which payment method generates the lowest revenue?
SELECT payment_method, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY payment_method
ORDER BY total_revenue ASC
LIMIT 1;

-- Q70.Which payment method is preferred by subscribed customers?
SELECT payment_method, COUNT(*) AS usage_count
FROM customer
WHERE subscription_status = 'Yes'
GROUP BY payment_method
ORDER BY usage_count DESC
LIMIT 1;

-- Q71.Which shipping type is used most often?
SELECT shipping_type, COUNT(*) AS usage_count
FROM customer
GROUP BY shipping_type
ORDER BY usage_count DESC
LIMIT 1;

-- Q72.Which shipping type generates the highest revenue?
SELECT shipping_type, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY shipping_type
ORDER BY total_revenue DESC
LIMIT 1;

-- Q73.Which locations prefer faster shipping options?
-- “faster shipping” = Express)
SELECT location, COUNT(*) AS express_count
FROM customer
WHERE shipping_type = 'Express'
GROUP BY location
ORDER BY express_count DESC
LIMIT 5;

-- Q74.Which product categories are mostly shipped via express shipping?
SELECT category, COUNT(*) AS express_count
FROM customer
WHERE shipping_type = 'Express'
GROUP BY category
ORDER BY express_count DESC
LIMIT 5;

-- Q75.Which shipping type is most common among repeat customers?
SELECT shipping_type, COUNT(*) AS repeat_count
FROM customer
WHERE previous_purchases > 0
GROUP BY shipping_type
ORDER BY repeat_count DESC
LIMIT 1;

-- Q76.Which payment method is most common among discount users?
SELECT payment_method, COUNT(*) AS discount_count
FROM customer
WHERE discount_applied = 'Yes'
GROUP BY payment_method
ORDER BY discount_count DESC
LIMIT 1;

-- Q77. Which payment method is preferred in each location?
SELECT location, payment_method, COUNT(*) AS count
FROM customer
GROUP BY location, payment_method
ORDER BY location, count DESC;

-- Q78.Which shipping option is most used during high sales seasons?
SELECT shipping_type, COUNT(*) AS count
FROM customer
WHERE season IN ('Winter', 'Holiday', 'Summer')  -- adjust your high-sales seasons
GROUP BY shipping_type
ORDER BY count DESC
LIMIT 1;

-- Q79.Which product category has the highest customer rating?
SELECT category, AVG(review_rating) AS avg_rating
FROM customer
GROUP BY category
ORDER BY avg_rating DESC
LIMIT 1;

-- Q80.Which combination of age group and category generates the highest revenue?
SELECT age_group, category, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group, category
ORDER BY total_revenue DESC
LIMIT 1;

-- Q81.Which location prefers which product category the most?
SELECT location, category, COUNT(*) AS count
FROM customer
GROUP BY location, category
ORDER BY location, count DESC;

-- Q82.Which customers give high ratings but spend less?
SELECT customer_id, review_rating, purchase_amount
FROM customer
WHERE review_rating >= 4
ORDER BY purchase_amount ASC
LIMIT 10;

-- Q83.Which products have high sales but low ratings?
-- SELECT item_purchased, SUM(purchase_amount) AS total_sales, AVG(review_rating) AS avg_rating
-- FROM customer
-- GROUP BY item_purchased
-- HAVING avg_rating <= 3
-- ORDER BY total_sales DESC
-- LIMIT 10;

-- Q84.Which categories perform best in each season?
SELECT season, category, SUM(purchase_amount) AS total_sales
FROM customer
GROUP BY season, category
ORDER BY season, total_sales DESC;

-- Q85.Which color is most popular in each season?
SELECT season, color, COUNT(1) AS count
FROM customer
GROUP BY season, color
ORDER BY season, count DESC;

-- Q86.Which size is most popular in each category?
SELECT category, size, COUNT(*) AS count
FROM customer
GROUP BY category, size
ORDER BY category, count DESC;

-- Q87.Which customer segments contribute most to seasonal sales?
SELECT age_group, season, SUM(purchase_amount) AS total_sales
FROM customer
GROUP BY age_group, season
ORDER BY total_sales DESC;

-- Q88.Which product categories grow fastest in repeat purchases?
SELECT category, SUM(previous_purchases) AS repeat_purchases
FROM customer
GROUP BY category
ORDER BY repeat_purchases DESC;

-- Q89.Which customers spend more during specific seasons?
SELECT customer_id, season, SUM(purchase_amount) AS total_spent
FROM customer
GROUP BY customer_id, season
ORDER BY season, total_spent DESC
LIMIT 10;

-- Q90.Which locations show the highest growth in repeat purchases?
SELECT location, SUM(previous_purchases) AS total_repeat
FROM customer
GROUP BY location
ORDER BY total_repeat DESC
LIMIT 5;

-- Q91.Which products maintain high ratings across all seasons?
-- SELECT item_purchased, MIN(review_rating) AS min_rating
-- FROM customer
-- GROUP BY item_purchased
-- HAVING min_rating >= 4
-- ORDER BY min_rating DESC;

-- Q92.Which combination of category, color, and season generates the highest revenue?
SELECT category, color, season, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY category, color, season
ORDER BY total_revenue DESC
LIMIT 1;


commit;